### ISSUE TITLE
Add punctuation in our own texts

### ISSUE THREAD

**Issue by CamilleSchr** [attilanagy234/neural-punctuator#11]
Hello,

I'm kind of new with BERT etc, sorry in advance for the question, but how and where in the code sould I add my own texts, in order to have in the output my texts with the punctuation ?

Thanks,
Camille

**Comment by bana513** [comment]
Hi!

In [src/evaluate.ipynb](https://github.com/attilanagy234/neural-punctuator/blob/main/src/evaluate.ipynb) we read a raw text from file, preprocess the text, then predict for it and lastly translate predictions back into a text with punctuation.

Relevant parts should be extracted to a function in order to use it in a real world application. Please, remove unnecessary cells and it should be fine.

**Comment by CamilleSchr** [comment]
OK I see, thank you :)
